### ISSUE TITLE
Snap version seems unusable

### ISSUE THREAD

**Issue by penlinaco** [ubuntu/gnome-boxes#5] opened 2023-01-01 04:57 UTC
Please forgive me if I'm posting in the wrong place. I have not been able to use the snap version of gnome-boxes for a long time; probably since Ubuntu 20.04. Every time I try to create a VM, it always returns a 'Failed to start' message. I have looked for a solution on the internet and have found one post (Reddit I believe) which stated that snap packages cannot access anything outside of the user's home folder. The ISO image I tried to create a virtual machine with was from my Downloads folder, and I tried changing permissions of the package with no results. Gnome-boxes from the Ubuntu repositories works as expected. Is there any way to fix this issue? Or is there possibly another use for this snap package besides creating virtual machines?

**Comment by kairand** [comment] 2023-01-23 20:02
@penlinaco I tried it using a fresh Ubuntu 22.04.1 LTS install. It is, indeed, unusable. It was giving the "failed to start" error with any .iso. But I found out that the cause seems to be a simple permissions issue.

To solve this problem, you need to use the Snap Store and activate these permissions for GNOME Boxes:

- kvm: allows access to the kvm device;
- Read system mount information and disk quotas;
- Pause or end any process on the system.

After that, I managed to install and use Linux Mint and Windows 10 virtual machines as expected.

**Comment by penlinaco** [comment] 2023-01-24 08:05
@KairanD Thank you ever so much for your reply, I will have to try enabling those permissions again. I'm away from my computer for a while (out of the country) but when I get a chance I will try it out and let you know the results!

Edit: @KairanD  After trying your suggestion it worked as expected. I'm not sure why I couldn't get it to work before, but happy everything is fine now. Thanks once again.

**Comment by kairand** [comment] 2023-01-31 10:55
@penlinaco I'm happy to know that it worked! Thank you for testing. :)

Maybe we should keep this issue open until a definitive solution is implemented. The vast majority of users will not know how to adjust permissions to make the app work.

**Comment by penlinaco** [comment] 2023-02-25 14:44
@KairanD I apologize, I reread your comment and agree it would be a good idea to keep this issue open until it is easier to set up.

**Comment by kenvandine** [comment] 2023-07-10 13:18
We've gotten most of the issues fixed now and just need to get all the necessary snap interfaces auto-connected.  Once that's done we'll be able to close this issue.

**Comment by penlinaco** [comment] 2023-07-11 23:13
@kenvandine That's awesome news! Thank you for all the hard work! Looking forward to trying it out.

**Closed as completed** 2023-07-28 13:40 UTC
